[System.Collections.ArrayList]$script:FunctionsForSBUse = @(
    ${Function:AddLastWriteTimeToRegKey}.Ast.Extent.Text
    ${Function:AddWinRMTrustLocalHost}.Ast.Extent.Text
    ${Function:GetElevation}.Ast.Extent.Text
    ${Function:GetModuleDependencies}.Ast.Extent.Text
    ${Function:GetMSIFileInfo}.Ast.Extent.Text
    ${Function:GetNativePath}.Ast.Extent.Text
    ${Function:InvokeModuleDependencies}.Ast.Extent.Text
    ${Function:InvokePSCompatibility}.Ast.Extent.Text
    ${Function:MaualPSGalleryModuleInstall}.Ast.Extent.Text
    ${Function:PauseForWarning}.Ast.Extent.Text
    ${Function:UnzipFile}.Ast.Extent.Text
    ${Function:Get-AllPackageInfo}.Ast.Extent.Text
    ${Function:Get-InstalledProgramsFromRegistry}.Ast.Extent.Text
    ${Function:Install-ChocolateyCmdLine}.Ast.Extent.Text
    ${Function:Install-Program}.Ast.Extent.Text
    ${Function:New-Runspace}.Ast.Extent.Text
    ${Function:Uninstall-Program}.Ast.Extent.Text
    ${Function:Update-ChocolateyEnv}.Ast.Extent.Text
    ${Function:Update-PackageManagement}.Ast.Extent.Text
)
