#
# Module manifest for module 'modmanifest'
#
# Generated by: Eric Kraus [MSFT] & Christian Glessner [MCTS]
#
# Generated on: 2/1/2009
#

@{

# These modules will be processed when the module manifest is loaded.
NestedModules = @()

# This GUID is used to uniquely identify this module.
GUID = '54568f6f-d49b-4b69-8035-d6c80fd51e47'

# The author of this module.
Author = 'Eric Kraus [MSFT] & Christian Glessner [MCTS]'

# The company or vendor for this module.
CompanyName = 'SPoshMod'

# The copyright statement for this module.
Copyright = '2009 All rights reserved'

# The version of this module.
ModuleVersion = '1.0'

# A description of this module.
Description = 'THE SharePoint PowerShell Module  http://codeplex.com/SPoshMod'

# The minimum version of PowerShell needed to use this module.
PowerShellVersion = '2.0'

# The CLR version required to use this module.
CLRVersion = '2.0'

# Functions to export from this manifest.
ExportedFunctions = '*'

# Aliases to export from this manifest.
ExportedAliases = '*'

# Variables to export from this manifest.
ExportedVariables = '*'

# Cmdlets to export from this manifest.
ExportedCmdlets = '*'

# This is a list of other modules that must be loaded before this module.
RequiredModules = @()

# The script files (.ps1) that are loaded before this module.
ScriptsToProcess = @()

# The type files (.ps1xml) loaded by this module.
TypesToProcess = @()

# The format files (.ps1xml) loaded by this module.
FormatsToProcess = @()

# A list of assemblies that must be loaded before this module can work.
RequiredAssemblies = @()

# Lists additional items like icons, etc. that the module will use.
OtherItems = @()

# Module specific private data can be passed via this member.
PrivateData = ''

}

